# Generated by Django 6.0.3 on 2026-03-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_paymentmethod'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='pan_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiry',
        ),
    ]
